<script setup lang='ts'>
import type { BoxProps } from '@nui/components'
import type { AnyString, ComponentFactory, NuanceColor, NuanceGradient, NuanceRadius, NuanceSize } from '@nui/types'

import { useVarsResolver } from '@nui/composables'
import { createVariantColorResolver, getRadius, getSize } from '@nui/utils'
import { computed } from 'vue'

import Box from '../box.vue'
import css from './avatar.module.css'
import { useAvatarGroupState } from './lib/context'
import { getInitials } from './lib/get-initials'
import { getInitialsColor } from './lib/get-initials-color'


type AvatarVariant = 'filled' | 'light' | 'gradient' | 'outline' | 'default'

type AvatarClasses = 'root' | 'placeholder' | 'image'

interface AvatarVars {
	root:
		| '--avatar-size'
		| '--avatar-radius'
		| '--avatar-bg'
		| '--avatar-color'
		| '--avatar-bd'
}

interface StyleProps {
	/** Border radius */
	radius?: NuanceRadius | AnyString

	/** Component size */
	size?: NuanceSize | AnyString

	/** Color from theme. Pass `'initials'` to derive the color from the user's name. */
	color?: NuanceColor | 'initials'

	/** Gradient configuration (used with `variant="gradient"`) */
	gradient?: NuanceGradient
}

interface Props extends BoxProps, StyleProps {
	/** Image URL. When the image fails to load or is `null`, a placeholder is shown instead. */
	src?: string | null

	/** Image `alt` attribute. Also used as `title` for the placeholder. */
	alt?: string

	/** Name of the user. Used to render initials and to generate a color when `color="initials"`. */
	name?: string

	/** Palette of colors picked from for autogenerated initials. Defaults to all theme colors except gray and dark. */
	allowedInitialsColors?: NuanceColor[]

	/**
	 * Icon rendered when no `src` and no `name` are provided
	 * @default 'gravity-ui:person'
	 */
	placeholder?: string
}

type AvatarFactory = ComponentFactory<{
	props: Props
	vars: AvatarVars
	variant: AvatarVariant
	classes: AvatarClasses
}>
export type AvatarProps = AvatarFactory['props']


const {
	name,
	radius,
	placeholder = 'gravity-ui:person',
	...props
} = defineProps<AvatarProps>()

const initials = computed(() => name && getInitials(name))
const ctx = useAvatarGroupState()

const style = useVarsResolver<AvatarFactory>(theme => {
	const color = props.color === 'initials' && typeof name === 'string'
		? getInitialsColor(name, props.allowedInitialsColors)
		: props.color

	const { background, text, border } = createVariantColorResolver({
		theme,
		gradient: props.gradient,
		color: color || 'gray',
		variant: props.variant || 'light',
	})

	return {
		root: {
			'--avatar-size': getSize(props.size, 'avatar-size'),
			'--avatar-radius': radius === undefined ? undefined : getRadius(radius),
			'--avatar-bg': color || props.variant ? background : undefined,
			'--avatar-color': color || props.variant ? text : undefined,
			'--avatar-bd': color || props.variant ? border : undefined,
		},
	}
})
</script>

<template>
	<Box
		:style='style.root'
		:class='[css.root, classes?.root]'
		:mod='[{ "within-group": ctx?.withinGroup }, mod]'
	>
		<span v-if='!src' :class='[css.placeholder, classes?.placeholder]' :title='alt'>
			<slot>
				<Icon v-if='!src && !name' :name='placeholder' />
				{{ initials }}
			</slot>
		</span>
		<NuxtImg
			v-else
			:src
			:alt
			:class='[css.image, classes?.image]'
		/>
	</Box>
</template>
