<script setup lang='ts'>
import type { BoxProps } from '@nui/components'
import type { NuanceColor, NuanceGradient, NuanceRadius, NuanceSize } from '@nui/types'

import { getInitialsColor } from '@nui/components/avatar/_lib/get-initials-color'
import { useStyleResolver } from '@nui/composals'
import { createVariantColorResolver, getRadius, getSize } from '@nui/utils'
import { computed } from 'vue'

import Box from '../box.vue'
import { useAvatarGroupState } from './_lib/context'
import { getInitials } from './_lib/get-initials'
import css from './avatar.module.css'


export interface AvatarProps extends BoxProps {
	/** Width and height of the avatar, numbers are converted to rem @default `'md'` */
	size?: NuanceSize | string

	/** Key of `theme.radius` or any valid CSS value to set border-radius @default `'1000px'` */
	radius?: NuanceRadius

	/** Key of `theme.colors` or any valid CSS color @default `'gray'` */
	color?: NuanceColor | 'initials'

	/** Gradient configuration for `variant="gradient"` @default `theme.defaultGradient` */
	gradient?: NuanceGradient

	/** Image url, if the image cannot be loaded or `src={null}`, then placeholder is displayed instead */
	src?: string | null

	/** Image `alt` attribute, also used as `title` attribute for placeholder */
	alt?: string

	/** Name of the user. When `src` is not set, used to display initials and to generate color when `color="initials"` is set. */
	name?: string

	/** A list of colors that is used for autogenerated initials. By default, all default colors can be used except gray and dark. */
	allowedInitialsColors?: NuanceColor[]

	/** Placeholder icon */
	placeholder?: string

	variant?: | 'filled' | 'light' | 'gradient' | 'outline' | 'default'
}

const {
	alt,
	src,
	mod,
	name,
	color,
	allowedInitialsColors,
	gradient,
	variant,
	size,
	radius,
	placeholder = 'gravity-ui:person',
} = defineProps<AvatarProps>()

const initials = computed(() => name && getInitials(name))
const ctx = useAvatarGroupState()

const style = computed(() => useStyleResolver(theme => {
	const _color = color === 'initials' && typeof name === 'string'
		? getInitialsColor(name, allowedInitialsColors)
		: color

	const { background, text, border } = createVariantColorResolver({
		color: _color || 'gray',
		theme,
		gradient,
		variant: variant || 'light',
	})

	return {
		'--avatar-size': getSize(size, 'avatar-size'),
		'--avatar-radius': radius === undefined ? undefined : getRadius(radius),
		'--avatar-bg': _color || variant ? background : undefined,
		'--avatar-color': _color || variant ? text : undefined,
		'--avatar-bd': _color || variant ? border : undefined,
	}
}))
</script>

<template>
	<Box :style :class='css.root' :mod='[{ "within-group": ctx?.withinGroup }, mod]'>
		<span v-if='!src' :class='css.placeholder' :title='alt'>
			<slot>
				<Icon v-if='!src && !name' :name='placeholder' />
				{{ initials }}
			</slot>
		</span>
		<NuxtImg
			v-else
			:src
			:alt
			:class='css.image'
		/>
	</Box>
</template>
