<script setup lang='ts'>
import type { BoxProps } from '@nui/components'
import type { NuanceColor, NuanceGradient, NuanceRadius, NuanceSize } from '@nui/types'

import { useStyleResolver } from '@nui/composables'
import { createVariantColorResolver, getRadius, getSize } from '@nui/utils'
import { computed } from 'vue'

import Box from '../box.vue'
import css from './avatar.module.css'
import { useAvatarGroupState } from './lib/context'
import { getInitials } from './lib/get-initials'
import { getInitialsColor } from './lib/get-initials-color'


export interface AvatarProps extends BoxProps {
	/** Component size */
	size?: NuanceSize | string

	/** Border radius */
	radius?: NuanceRadius

	/** Color from theme. Pass `'initials'` to derive the color from the user's name. */
	color?: NuanceColor | 'initials'

	/** Gradient configuration (used with `variant="gradient"`) */
	gradient?: NuanceGradient

	/** Image URL. When the image fails to load or is `null`, a placeholder is shown instead. */
	src?: string | null

	/** Image `alt` attribute. Also used as `title` for the placeholder. */
	alt?: string

	/** Name of the user. Used to render initials and to generate a color when `color="initials"`. */
	name?: string

	/** Palette of colors picked from for autogenerated initials. Defaults to all theme colors except gray and dark. */
	allowedInitialsColors?: NuanceColor[]

	/**
	 * Icon rendered when no `src` and no `name` are provided
	 * @default 'gravity-ui:person'
	 */
	placeholder?: string

	/** Visual variant */
	variant?: | 'filled' | 'light' | 'gradient' | 'outline' | 'default'
}

const {
	alt,
	src,
	mod,
	name,
	color,
	allowedInitialsColors,
	gradient,
	variant,
	size,
	radius,
	placeholder = 'gravity-ui:person',
} = defineProps<AvatarProps>()

const initials = computed(() => name && getInitials(name))
const ctx = useAvatarGroupState()

const style = computed(() => useStyleResolver(theme => {
	const _color = color === 'initials' && typeof name === 'string'
		? getInitialsColor(name, allowedInitialsColors)
		: color

	const { background, text, border } = createVariantColorResolver({
		color: _color || 'gray',
		theme,
		gradient,
		variant: variant || 'light',
	})

	return {
		'--avatar-size': getSize(size, 'avatar-size'),
		'--avatar-radius': radius === undefined ? undefined : getRadius(radius),
		'--avatar-bg': _color || variant ? background : undefined,
		'--avatar-color': _color || variant ? text : undefined,
		'--avatar-bd': _color || variant ? border : undefined,
	}
}))
</script>

<template>
	<Box :style :class='css.root' :mod='[{ "within-group": ctx?.withinGroup }, mod]'>
		<span v-if='!src' :class='css.placeholder' :title='alt'>
			<slot>
				<Icon v-if='!src && !name' :name='placeholder' />
				{{ initials }}
			</slot>
		</span>
		<NuxtImg
			v-else
			:src
			:alt
			:class='css.image'
		/>
	</Box>
</template>
